//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles True and False.
        /// </summary>
        internal static string BoolButtonDescription {
            get {
                return ResourceManager.GetString("BoolButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to returns a boolean..
        /// </summary>
        internal static string BoolButtonPortDataOutputToolTip {
            get {
                return ResourceManager.GetString("BoolButtonPortDataOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes a list of values and returns the selected item and index..
        /// </summary>
        internal static string DropdownDescription {
            get {
                return ResourceManager.GetString("DropdownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input a list..
        /// </summary>
        internal static string DropdownPortDataInputToolTip {
            get {
                return ResourceManager.GetString("DropdownPortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index of the selected value..
        /// </summary>
        internal static string DropdownPortDataOutputIndexToolTip {
            get {
                return ResourceManager.GetString("DropdownPortDataOutputIndexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the selected item..
        /// </summary>
        internal static string DropdownPortDataOutputValueToolTip {
            get {
                return ResourceManager.GetString("DropdownPortDataOutputValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input any.
        /// </summary>
        internal static string HelloDynamoPortDataInputToolTip {
            get {
                return ResourceManager.GetString("HelloDynamoPortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result..
        /// </summary>
        internal static string HelloDynamoPortDataOutputToolTip {
            get {
                return ResourceManager.GetString("HelloDynamoPortDataOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes a list of doubles and diyplays them as ParallelCoordinates.
        /// </summary>
        internal static string ParallelCoordinatesDescription {
            get {
                return ResourceManager.GetString("ParallelCoordinatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ParallelCoordinatesPortDataInputToolTip {
            get {
                return ResourceManager.GetString("ParallelCoordinatesPortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Item.
        /// </summary>
        internal static string ParallelCoordinatesPortDataOutputToolTip {
            get {
                return ResourceManager.GetString("ParallelCoordinatesPortDataOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sample UI node which displays custom UI..
        /// </summary>
        internal static string UtilitiesDescription {
            get {
                return ResourceManager.GetString("UtilitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a list..
        /// </summary>
        internal static string UtilitiesPortDataInputToolTip {
            get {
                return ResourceManager.GetString("UtilitiesPortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result..
        /// </summary>
        internal static string UtilitiesPortDataOutputToolTip {
            get {
                return ResourceManager.GetString("UtilitiesPortDataOutputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes a list of doubles and displays the values as graph or histogram..
        /// </summary>
        internal static string Watch2dDescription {
            get {
                return ResourceManager.GetString("Watch2dDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input a list of doubles..
        /// </summary>
        internal static string Watch2dPortDataInputToolTip {
            get {
                return ResourceManager.GetString("Watch2dPortDataInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to returns the input..
        /// </summary>
        internal static string Watch2dPortDataOutputToolTip {
            get {
                return ResourceManager.GetString("Watch2dPortDataOutputToolTip", resourceCulture);
            }
        }
    }
}
